const appLinks = [
    {
        "id": 1,
        "name": "Sharavarsh",
        "image": "https://i.postimg.cc/MHWg56H0/sharavarsh.jpg",
        "description":"",
        "appstore":"",
        "playstore":"",
        "youtube":"",
        "apk":"",
        "pwa":"",
        "district":"kasargode"
    },
    {
        "id": 2,
        "name": "Leader",
        "image": "https://i.postimg.cc/2jVJxSzw/Leader.png",
        "description":"",
        "appstore":"",
        "playstore":"",
        "youtube":"",
        "apk":"",
        "pwa":"",
        "district":"kannur"
    },
    {
        "id": 3,
        "name": "Azad",
        "image": "https://i.postimg.cc/B6vxBRsL/Azad.jpg",
        "description":"",
        "appstore":"",
        "playstore":"",
        "youtube":"",
        "apk":"",
        "pwa":"",
        "district":"Wayanad"
    },
    {
        "id": 4,
        "name": "Mahatma",
        "image": "https://i.postimg.cc/B6ymz2qC/Mahatma-App.jpg",
        "description":"",
        "appstore":"",
        "playstore":"https://play.google.com/store/apps/details?id=com.plusitbusinesspark.dcckozhikode",
        "youtube":"",
        "apk":"",
        "pwa":"",
        "district":"Kozhikode"
    },
    {
        "id": 5,
        "name": "Quit India",
        "image": "https://i.postimg.cc/7Lt9CSTy/Quit-India.png",
        "description":"",
        "appstore":"",
        "playstore":"https://play.google.com/store/apps/details?id=com.plusitbusinesspark.dccmalappuram",
        "youtube":"",
        "apk":"",
        "pwa":"",
        "district":"Malappuram"
    },
    {
        "id": 6,
        "name": "Nethaji",
        "image": "https://i.postimg.cc/X7gwG9TD/Nethaji-app.png",
        "description":"",
        "appstore":"https://apps.apple.com/in/app/netaji/id6484161192",
        "playstore":"",
        "youtube":"",
        "apk":"https://drive.google.com/file/d/1uBQnlkjCPLPJNA7f5XfVcQtp7dUJLYpx/view?usp=sharing",
        "pwa":"",
        "district":"Palakkad"
    },
    {
        "id": 7,
        "name": "Sadhbhavana",
        "image": "https://i.postimg.cc/GhzyhdyW/Sadhbhavana.png",
        "description":"",
        "appstore":"https://apps.apple.com/in/app/sadhbhavana/id6479501831",
        "playstore":"https://play.google.com/store/apps/details?id=com.plusitbusinesspark.dcctcr",
        "youtube":"",
        "apk":"",
        "pwa":"https://sadhbhavana.dmckpcc.in/",
        "district":"Thrissur"
    },
    {
        "id": 8,
        "name": "Swadheshi",
        "image": "https://i.postimg.cc/MT8TmFB0/Swadheshi.png",
        "description":"",
        "appstore":"",
        "playstore":"https://play.google.com/store/apps/details?id=com.plusitbusinesspark.dccernakulam",
        "youtube":"",
        "apk":"",
        "pwa":"",
        "district":"Ernakulam"
    },
    {
        "id": 9,
        "name": "Samaragni",
        "image": "https://i.postimg.cc/HkqsTh6G/Smaragni.jpg",
        "description":"",
        "appstore":"",
        "playstore":"https://play.google.com/store/apps/details?id=com.plusitbusinesspark.dccidukki",
        "youtube":"",
        "apk":"",
        "pwa":"",
        "district":"Idukki"
    },
    {
        "id": 10,
        "name": "Sabarmathi",
        "image": "https://i.postimg.cc/Wp5Nd35w/Sabarmathi.png",
        "description":"",
        "appstore":"",
        "playstore":"https://play.google.com/store/apps/details?id=com.plusitbusinesspark.dcckottayam",
        "youtube":"",
        "apk":"",
        "pwa":"",
        "district":"Kottayam"
    },
    {
        "id": 11,
        "name": "Indhiraji",
        "image": "https://i.postimg.cc/Dy4PDVG1/Indhiraji.jpg",
        "description":"",
        "appstore":"",
        "playstore":"https://play.google.com/store/apps/details?id=com.plusitbusinesspark.dccalappuzha",
        "youtube":"",
        "apk":"",
        "pwa":"",
        "district":"Alappuzha"
    },
    {
        "id": 12,
        "name": "1947",
        "image": "https://i.postimg.cc/43ftXjYL/Apk1947.png",
        "description":"",
        "appstore":"",
        "playstore":"https://play.google.com/store/apps/details?id=com.plusitbusinesspark.dccpathanamthitta",
        "youtube":"",
        "apk":"",
        "pwa":"",
        "district":"Pathanamthitta"
    },
    {
        "id": 13,
        "name": "Charkha",
        "image": "https://i.postimg.cc/YCJVVfjC/Charkha.jpg",
        "description":"",
        "appstore":"",
        "playstore":"https://play.google.com/store/apps/details?id=com.plusitbusinesspark.dcckollam",
        "youtube":"",
        "apk":"",
        "pwa":"",
        "district":"Kollam"
    },
    {
        "id": 14,
        "name": "Vandemataram",
        "image": "https://i.postimg.cc/rskqk2mz/Vademataram.jpg",
        "description":"",
        "appstore":"https://apps.apple.com/in/app/vande-mataram/id6482974454",
        "playstore":"https://play.google.com/store/apps/details?id=com.plusitbusinesspark.dccthiruvanathapuram",
        "youtube":"",
        "apk":"",
        "pwa":"",
        "district":"Thiruvananthapuram"
    }
]

module.exports = {appLinks}